# generated by Neptune Namespaces v1.x.x
# file: Art/Foundation/Browser/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Browser ||
Foundation.addNamespace 'Browser', class Browser extends Neptune.Base
  ;