# generated by Neptune Namespaces
# file: perfs/javascript/index.coffee

module.exports =
Javascript                                   = require './namespace'
Javascript.ElementCreationArgumentProcessing = require './element_creation_argument_processing'
Javascript.GetterSetter                      = require './getter_setter'
Javascript.Math                              = require './math'
Javascript.MembersAndLocals                  = require './members_and_locals'
Javascript.MethodInvocation                  = require './method_invocation'
Javascript.ObjectsAndArrays                  = require './objects_and_arrays'
Javascript.ParameterPassing                  = require './parameter_passing'
Javascript.finishLoad(
  ["ElementCreationArgumentProcessing","GetterSetter","Math","MembersAndLocals","MethodInvocation","ObjectsAndArrays","ParameterPassing"]
)