# generated by Neptune Namespaces v3.x.x
# file: perfs/javascript/namespace.coffee

module.exports = (require '../namespace').addNamespace('Javascript', class Javascript extends Neptune.PackageNamespace)
