# generated by Neptune Namespaces v0.4.1
# file: perfs/javascript/namespace.coffee

Perfs = require '../namespace'
module.exports = Perfs.Javascript ||
Perfs.addNamespace 'Javascript', class Javascript extends Neptune.Base
  ;