# generated by Neptune Namespaces
# file: perf/perfs/javascript/namespace.coffee

Perfs = require '../namespace'
module.exports = Perfs.Javascript ||
class Perfs.Javascript extends Neptune.Base
  @namespace: Perfs
  @namespacePath: "Neptune.Perfs.Javascript"

Perfs.addNamespace Perfs.Javascript