# generated by Neptune Namespaces
# this file: test/art/foundation/browser/index.coffee

module.exports =
Browser         = require './namespace'
Browser.Browser = require './browser'
Browser.finishLoad(
  ["Browser"]
  []
)