# generated by Neptune Namespaces
# file: test/art/foundation/browser/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Browser ||
class Foundation.Browser extends Neptune.Base
  @namespace: Foundation
  @namespacePath: "Neptune.Art.Foundation.Browser"