# generated by Neptune Namespaces v2.x.x
# file: Art/Foundation/namespace.coffee

Art = require '../namespace'
module.exports = Art.Foundation ||
Art.addNamespace 'Foundation', class Foundation extends Neptune.Base
  ;
require './Binary/namespace';
require './Browser/namespace';
require './Tools/namespace'