# generated by Neptune Namespaces v1.x.x
# file: Art/Foundation/namespace.coffee

Art = require '../namespace'
module.exports = Art.Foundation ||
Art.addNamespace 'Foundation', class Foundation extends Neptune.Base
  ;