# generated by Neptune Namespaces v1.x.x
# file: art/foundation/standard_lib/inspect/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_inspect'
.addModules
  FormattedInspect:       require './formatted_inspect'       
  InspectedObjectLiteral: require './inspected_object_literal'
  Inspector:              require './inspector'               
  Inspector2:             require './inspector2'              
  ToInspectedObjects:     require './to_inspected_objects'    
  ToPlainObjects:         require './to_plain_objects'        
require './inspected'