# generated by Neptune Namespaces v0.5
# file: art/foundation/standard_lib/inspect/namespace.coffee

StandardLib = require '../namespace'
module.exports = StandardLib.Inspect ||
StandardLib.addNamespace 'Inspect', class Inspect extends Neptune.Base
  ;