# generated by Neptune Namespaces v0.5
# file: tests/art/foundation/tools/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Tools ||
Foundation.addNamespace 'Tools', class Tools extends Neptune.Base
  ;