# generated by Neptune Namespaces v0.4.1
# file: tests/art/foundation/tools/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Tools ||
Foundation.addNamespace 'Tools', class Tools extends Neptune.Base
  ;