# generated by Neptune Namespaces
# file: test/art/foundation/inspect/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Inspect ||
class Foundation.Inspect extends Neptune.Base
  @namespace: Foundation
  @namespacePath: "Neptune.Art.Foundation.Inspect"