# generated by Neptune Namespaces
# this file: src/art/index.coffee

module.exports =
Art            = require './namespace'
Art.DevTools   = require './dev_tools'
Art.Foundation = require './foundation'
Art.finishLoad(
  []
  ["DevTools","Foundation"]
)