# generated by Neptune Namespaces
# file: art/index.coffee

module.exports =
Art            = require './namespace'
Art.DevTools   = require './dev_tools'
Art.Foundation = require './foundation'
Art.finishLoad(
  []
)