# generated by Neptune Namespaces
# file: src/art/namespace.coffee

self.Neptune ||= class Neptune
  @namespacePath: "Neptune"
  @Base: class Base
    @finishLoad: (classes)->
      for childName in classes when child = @[child]
        child.namespace = @
        child.namespacePath = @namespacePath + "." + child

module.exports = Neptune.Art ||
class Neptune.Art extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.Art"