# generated by Neptune Namespaces v1.x.x
# file: Art/DevTools/Test/index.coffee

module.exports = require './namespace'
.addModules
  ArtChai:              require './art_chai'              
  MochaBrowserReporter: require './mocha_browser_reporter'
  Mocha:                require './mocha'                 
  Perf:                 require './perf'                  