# generated by Neptune Namespaces v1.x.x
# file: Art/DevTools/Test/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.Test ||
DevTools.addNamespace 'Test', class Test extends Neptune.Base
  ;