# generated by Neptune Namespaces
# this file: test/art/foundation/async/index.coffee

module.exports =
Async          = require './namespace'
Async.Basic    = require './basic'
Async.Join     = require './join'
Async.Sequence = require './sequence'
Async.finishLoad(
  ["Basic","Join","Sequence"]
  []
)