# generated by Neptune Namespaces
# file: test/art/foundation/async/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Async ||
class Foundation.Async extends Neptune.Base
  @namespace: Foundation
  @namespacePath: "Neptune.Art.Foundation.Async"