# generated by Neptune Namespaces v1.x.x
# file: tests/art/foundation/index.coffee

module.exports = require './namespace'
require './ClassSystem'
require './binary'
require './browser'
require './tools'