# generated by Neptune Namespaces v2.x.x
# file: tests/art/foundation/namespace.coffee

Art = require '../namespace'
module.exports = Art.Foundation ||
Art.addNamespace 'Foundation', class Foundation extends Neptune.Base
  ;
require './binary/namespace';
require './browser/namespace';
require './tools/namespace'