# generated by Neptune Namespaces v1.x.x
# file: art/foundation/tools/ArtConfig/index.coffee

module.exports = require './namespace'
.addModules
  Config:         require './Config'        
  ConfigRegistry: require './ConfigRegistry'
  Configurable:   require './Configurable'  