# generated by Neptune Namespaces
# file: test/art/foundation/binary/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Binary ||
class Foundation.Binary extends Neptune.Base
  @namespace: Foundation
  @namespacePath: "Neptune.Art.Foundation.Binary"