# generated by Neptune Namespaces
# file: tests/art/dev_tools/index.coffee

module.exports =
DevTools            = require './namespace'
DevTools.DomConsole = require './dom_console'
DevTools.finishLoad(
  ["DomConsole"]
)