# generated by Neptune Namespaces v0.5
# file: tests/art/dev_tools/namespace.coffee

Art = require '../namespace'
module.exports = Art.DevTools ||
Art.addNamespace 'DevTools', class DevTools extends Neptune.Base
  ;