# generated by Neptune Namespaces
# file: tests/art/dev_tools/namespace.coffee

Art = require '../namespace'
module.exports = Art.DevTools ||
class Art.DevTools extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Tests.Art.DevTools"

Art.addNamespace Art.DevTools