# generated by Neptune Namespaces v2.x.x
# file: tests/art/dev_tools/namespace.coffee

Art = require '../namespace'
module.exports = Art.DevTools ||
Art.addNamespace 'DevTools', class DevTools extends Neptune.Base
  ;
