# generated by Neptune Namespaces
# this file: src/art/foundation/inspect/index.coffee

module.exports =
Inspect            = require './namespace'
Inspect.Inspected  = require './inspected'
Inspect.Inspector  = require './inspector'
Inspect.Inspector2 = require './inspector2'
Inspect.Main       = require './main'
Inspect.finishLoad(
  ["Inspector","Inspector2","Main"]
  ["Inspected"]
)