# generated by Neptune Namespaces
# file: src/art/foundation/inspect/inspected/namespace.coffee

Inspect = require '../namespace'
module.exports = Inspect.Inspected ||
class Inspect.Inspected extends Neptune.Base
  @namespace: Inspect
  @namespacePath: "Neptune.Art.Foundation.Inspect.Inspected"

Inspect.addNamespace Inspect.Inspected