# generated by Neptune Namespaces v2.x.x
# file: Art/DevTools/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Test: require './Test'
require './DomConsole'
require './Webpack'