# generated by Neptune Namespaces v2.x.x
# file: Art/DevTools/namespace.coffee

Art = require '../namespace'
module.exports = Art.DevTools ||
Art.addNamespace 'DevTools', class DevTools extends Neptune.Base
  ;
require './DomConsole/namespace';
require './Webpack/namespace'