# generated by Neptune Namespaces v2.x.x
# file: Art/DevTools/Webpack/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.Webpack ||
DevTools.addNamespace 'Webpack', class Webpack extends Neptune.Base
  ;
