# generated by Neptune Namespaces v1.x.x
# file: Art/Foundation/ClassSystem/index.coffee

module.exports = require './namespace'
.includeInNamespace require './ClassSystem'
.addModules
  BaseObject:       require './BaseObject'      
  WebpackHotLoader: require './WebpackHotLoader'