# generated by Neptune Namespaces v1.x.x
# file: Art/DevTools/DomConsole/index.coffee

module.exports = require './namespace'
.includeInNamespace require './DomConsole'
.addModules
  Chart:   require './Chart'  
  Console: require './Console'
  ToolBar: require './ToolBar'
require './PseudoReact'