# generated by Neptune Namespaces v2.x.x
# file: Art/DevTools/DomConsole/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.DomConsole ||
DevTools.addNamespace 'DomConsole', class DomConsole extends Neptune.Base
  ;
require './PseudoReact/namespace'