# generated by Neptune Namespaces v1.x.x
# file: tests/art/foundation/ClassSystem/BaseObject/namespace.coffee

ClassSystem = require '../namespace'
module.exports = ClassSystem.BaseObject ||
ClassSystem.addNamespace 'BaseObject', class BaseObject extends Neptune.Base
  ;