# generated by Neptune Namespaces v0.3.0
# file: art/dev_tools/dom_console/pseudo_react/namespace.coffee

DomConsole = require '../namespace'
module.exports = DomConsole.PseudoReact ||
DomConsole.addNamespace 'PseudoReact', class PseudoReact extends Neptune.Base
  ;