# generated by Neptune Namespaces
# file: art/foundation/async/index.coffee

(module.exports = require './namespace')
.addModules
  _All:            require './_all'
  Basic:           require './basic'
  ProgressAdapter: require './progress_adapter'
