# generated by Neptune Namespaces v0.1.0
# file: art/foundation/async/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './_async')
.addModules
  ProgressAdapter: require './progress_adapter'