# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/ForHumans/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './ForHumans'
.addModules
  HumanStringFormatting: require './HumanStringFormatting'