# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/ForHumans/namespace.coffee

module.exports = (require '../namespace').addNamespace('ForHumans', class ForHumans extends Neptune.PackageNamespace)
