# generated by Neptune Namespaces v3.x.x
# file: perfs/art/foundation/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Eq:            require './eq'            
  Hash:          require './hash'          
  StringParsing: require './string_parsing'
  Types:         require './types'         
  Unique:        require './unique'        
require './binary'