# generated by Neptune Namespaces
# file: perfs/art/foundation/index.coffee

module.exports =
Foundation               = require './namespace'
Foundation.Eq            = require './eq'
Foundation.Hash          = require './hash'
Foundation.StringParsing = require './string_parsing'
Foundation.Types         = require './types'
Foundation.Unique        = require './unique'
Foundation.Binary        = require './binary'
Foundation.finishLoad(
  ["Eq","Hash","StringParsing","Types","Unique"]
)