# generated by Neptune Namespaces v0.5
# file: perfs/art/foundation/namespace.coffee

Art = require '../namespace'
module.exports = Art.Foundation ||
Art.addNamespace 'Foundation', class Foundation extends Neptune.Base
  ;