# generated by Neptune Namespaces
# file: art/foundation/class_system/index.coffee

(module.exports = require './namespace')
.addModules
  _All:              require './_all'
  BaseModule:        require './base_module'
  BaseObject:        require './base_object'
  Clone:             require './clone'
  Log:               require './log'
  Map:               require './map'
  ObjectTreeFactory: require './object_tree_factory'
  WebpackHotLoader:  require './webpack_hot_loader'
require './inspect'