# generated by Neptune Namespaces v1.x.x
# file: art/foundation/class_system/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_class_system'
.addModules
  BaseModule:       require './base_module'       
  BaseObject:       require './base_object'       
  WebpackHotLoader: require './webpack_hot_loader'