# generated by Neptune Namespaces v0.3.0
# file: art/foundation/class_system/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './_class_system')
.addModules
  BaseModule:        require './base_module'
  BaseObject:        require './base_object'
  CallStack:         require './call_stack'
  Clone:             require './clone'
  Log:               require './log'
  Map:               require './map'
  ObjectTreeFactory: require './object_tree_factory'
  WebpackHotLoader:  require './webpack_hot_loader'
require './inspect'