# generated by Neptune Namespaces
# file: art/foundation/class_system/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.ClassSystem ||
Foundation.addNamespace class ClassSystem extends Neptune.Base
  ;