# generated by Neptune Namespaces v0.3.0
# file: art/foundation/class_system/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.ClassSystem ||
Foundation.addNamespace 'ClassSystem', class ClassSystem extends Neptune.Base
  ;