# generated by Neptune Namespaces v1.x.x
# file: art/foundation/class_system/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.ClassSystem ||
Foundation.addNamespace 'ClassSystem', class ClassSystem extends Neptune.Base
  ;