# generated by Neptune Namespaces v1.x.x
# file: Art/Foundation/Browser/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Browser'
.addModules
  Cookie:              require './Cookie'             
  Dom:                 require './Dom'                
  DomElementFactories: require './DomElementFactories'
  File:                require './File'               