# generated by Neptune Namespaces v0.5
# file: art/foundation/standard_lib/inspect/inspected/index.coffee

module.exports = require './namespace'
.addModules
  Array:  require './array' 
  Core:   require './core'  
  Object: require './object'
  String: require './string'