# generated by Neptune Namespaces v0.5
# file: art/foundation/standard_lib/inspect/inspected/namespace.coffee

Inspect = require '../namespace'
module.exports = Inspect.Inspected ||
Inspect.addNamespace 'Inspected', class Inspected extends Neptune.Base
  ;