# generated by Neptune Namespaces v1.x.x
# file: art/foundation/standard_lib/inspect/inspected/namespace.coffee

Inspect = require '../namespace'
module.exports = Inspect.Inspected ||
Inspect.addNamespace 'Inspected', class Inspected extends Neptune.Base
  ;