# generated by Neptune Namespaces v0.5
# file: tests/art/foundation/StandardLib/index.coffee

module.exports = require './namespace'
.addModules
  Array:      require './array'      
  Eq:         require './eq'         
  Hash:       require './hash'       
  Math:       require './math'       
  NextTick:   require './nextTick'   
  ObjectDiff: require './object_diff'
  ParseUrl:   require './parse_url'  
  PlainData:  require './plain_data' 
  Promise:    require './promise'    
  Regexp:     require './regexp'     
  Ruby:       require './ruby'       
  StringCase: require './string_case'
  String:     require './string'     
  Time:       require './time'       
  Types:      require './types'      
  Unique:     require './unique'     