# generated by Neptune Namespaces v1.x.x
# file: tests/art/foundation/StandardLib/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.StandardLib ||
Foundation.addNamespace 'StandardLib', class StandardLib extends Neptune.Base
  ;