# generated by Neptune Namespaces v1.x.x
# file: tests/art/foundation/tools/Config/index.coffee

module.exports = require './namespace'
.addModules
  ConfigRegistry:   require './ConfigRegistry'  
  TestConfig:       require './TestConfig'      
  TestConfigurable: require './TestConfigurable'