# generated by Neptune Namespaces v1.x.x
# file: tests/art/foundation/tools/Config/namespace.coffee

Tools = require '../namespace'
module.exports = Tools.Config ||
Tools.addNamespace 'Config', class Config extends Neptune.Base
  ;