# generated by Neptune Namespaces v0.1.0
# file: art/foundation/binary/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './_binary')
.addModules
  BinaryString: require './binary_string'
  EncodedImage: require './encoded_image'
  File:         require './file'
  Stream:       require './stream'
  Utf8:         require './utf8'
  WriteStream:  require './write_stream'