# generated by Neptune Namespaces
# file: art/foundation/binary/index.coffee

(module.exports = require './namespace')
.addModules
  _All:         require './_all'
  BinaryString: require './binary_string'
  EncodedImage: require './encoded_image'
  File:         require './file'
  Stream:       require './stream'
  Utf8:         require './utf8'
  WriteStream:  require './write_stream'
