# generated by Neptune Namespaces v0.5
# file: art/foundation/binary/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Binary ||
Foundation.addNamespace 'Binary', class Binary extends Neptune.Base
  ;