# generated by Neptune Namespaces
# file: art/foundation/binary/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Binary ||
Foundation.addNamespace class Binary extends Neptune.Base
  ;