# generated by Neptune Namespaces v0.5
# file: tests/art/foundation/ClassSystem/index.coffee

module.exports = require './namespace'
.addModules
  BaseObject: require './base_object'
  CallStack:  require './call_stack' 
  Clone:      require './clone'      
  Map:        require './map'        