# generated by Neptune Namespaces v0.5
# file: tests/art/foundation/ClassSystem/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.ClassSystem ||
Foundation.addNamespace 'ClassSystem', class ClassSystem extends Neptune.Base
  ;