# generated by Neptune Namespaces v0.1.0
# file: art/foundation/tools/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Tools ||
Foundation.addNamespace class Tools extends Neptune.Base
  ;