# generated by Neptune Namespaces
# this file: tests/art/foundation/inspect/index.coffee

module.exports =
Inspect            = require './namespace'
Inspect.Inspected  = require './inspected'
Inspect.Inspector2 = require './inspector2'
Inspect.Main       = require './main'
Inspect.finishLoad(
  ["Inspected","Inspector2","Main"]
  []
)