# generated by Neptune Namespaces v0.3.0
# file: tests/art/foundation/inspect/index.coffee

(module.exports = require './namespace')
.addModules
  FormattedInspect:   require './formatted_inspect'
  Inspected:          require './inspected'
  Inspector2:         require './inspector2'
  Main:               require './main'
  ToInspectedObjects: require './to_inspected_objects'