# generated by Neptune Namespaces v0.1.0
# file: tests/art/foundation/inspect/index.coffee

(module.exports = require './namespace')
.addModules
  Inspected:  require './inspected'
  Inspector2: require './inspector2'
  Main:       require './main'