# generated by Neptune Namespaces v1.x.x
# file: tests/art/foundation/inspect/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Inspect ||
Foundation.addNamespace 'Inspect', class Inspect extends Neptune.Base
  ;