# generated by Neptune Namespaces v0.4.1
# file: tests/art/foundation/inspect/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Inspect ||
Foundation.addNamespace 'Inspect', class Inspect extends Neptune.Base
  ;