# generated by Neptune Namespaces
# this file: src/art/dev_tools/index.coffee

module.exports =
DevTools            = require './namespace'
DevTools.DomConsole = require './dom_console'
DevTools.Profiler   = require './profiler'
DevTools.Test       = require './test'
DevTools.finishLoad(
  []
  ["DomConsole","Profiler","Test"]
)