# generated by Neptune Namespaces
# file: perfs/art/foundation/binary/index.coffee

module.exports =
Binary              = require './namespace'
Binary.BinaryString = require './binary_string'
Binary.finishLoad(
  ["BinaryString"]
)