# generated by Neptune Namespaces v3.x.x
# file: perfs/art/foundation/binary/namespace.coffee

module.exports = (require '../namespace').addNamespace('Binary', class Binary extends Neptune.PackageNamespace)
