# generated by Neptune Namespaces v1.x.x
# file: perfs/art/foundation/binary/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Binary ||
Foundation.addNamespace 'Binary', class Binary extends Neptune.Base
  ;