# generated by Neptune Namespaces
# file: perfs/index.coffee

module.exports =
Perfs            = require './namespace'
Perfs.Art        = require './art'
Perfs.Javascript = require './javascript'
Perfs.finishLoad(
  []
)