# generated by Neptune Namespaces v1.x.x
# file: Art/DevTools/DomConsole/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_dom_console'
.addModules
  Chart:   require './chart'   
  Console: require './console' 
  ToolBar: require './tool_bar'
require './pseudo_react'