# generated by Neptune Namespaces v0.5
# file: tests/art/foundation/standard_lib/index.coffee

module.exports = require './namespace'
.addModules
  ParseUrl:   require './parse_url'  
  Ruby:       require './ruby'       
  StringCase: require './string_case'
  String:     require './string'     