# generated by Neptune Namespaces v0.1.0
# file: tests/art/foundation/standard_lib/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.StandardLib ||
Foundation.addNamespace class StandardLib extends Neptune.Base
  ;