# generated by Neptune Namespaces v0.3.0
# file: tests/art/foundation/standard_lib/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.StandardLib ||
Foundation.addNamespace 'StandardLib', class StandardLib extends Neptune.Base
  ;