# generated by Neptune Namespaces v0.1.0
# file: art/foundation/class_system/inspect/inspected/index.coffee

(module.exports = require './namespace')
.addModules
  Array:  require './array'
  Core:   require './core'
  Object: require './object'
  String: require './string'