# generated by Neptune Namespaces
# file: art/foundation/class_system/inspect/inspected/index.coffee

module.exports =
Inspected        = require './namespace'
Inspected.Array  = require './array'
Inspected.Core   = require './core'
Inspected.Object = require './object'
Inspected.String = require './string'
Inspected.finishLoad(
  ["Array","Core","Object","String"]
)