# generated by Neptune Namespaces
# file: art/foundation/class_system/inspect/inspected/namespace.coffee

Inspect = require '../namespace'
module.exports = Inspect.Inspected ||
class Inspect.Inspected extends Neptune.Base
  @namespace: Inspect
  @namespacePath: "Neptune.Art.Foundation.ClassSystem.Inspect.Inspected"

Inspect.addNamespace Inspect.Inspected