# generated by Neptune Namespaces v0.1.0
# file: art/foundation/class_system/inspect/inspected/namespace.coffee

Inspect = require '../namespace'
module.exports = Inspect.Inspected ||
Inspect.addNamespace 'Inspected', class Inspected extends Neptune.Base
  ;