# generated by Neptune Namespaces v3.x.x
# file: tests/art/foundation/binary/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BinaryString: require './binary_string'
  EncodedImage: require './encoded_image'
  Utf8:         require './utf8'         
  WriteStream:  require './write_stream' 