# generated by Neptune Namespaces
# this file: test/tests/art/foundation/binary/index.coffee

module.exports =
Binary              = require './namespace'
Binary.EncodedImage = require './encoded_image'
Binary.String       = require './string'
Binary.Utf8         = require './utf8'
Binary.finishLoad(
  ["EncodedImage","String","Utf8"]
)