# generated by Neptune Namespaces
# file: tests/art/foundation/binary/index.coffee

module.exports =
Binary              = require './namespace'
Binary.BinaryString = require './binary_string'
Binary.EncodedImage = require './encoded_image'
Binary.Utf8         = require './utf8'
Binary.WriteStream  = require './write_stream'
Binary.finishLoad(
  ["BinaryString","EncodedImage","Utf8","WriteStream"]
)