# generated by Neptune Namespaces
# file: test/tests/art/foundation/binary/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Binary ||
class Foundation.Binary extends Neptune.Base
  @namespace: Foundation
  @namespacePath: "Neptune.Tests.Art.Foundation.Binary"

Foundation.addNamespace Foundation.Binary