# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/Binary/namespace.coffee

module.exports = (require '../namespace').addNamespace('Binary', class Binary extends Neptune.PackageNamespace)
