# generated by Neptune Namespaces
# file: art/foundation/standard_lib/index.coffee

module.exports =
StandardLib                    = require './namespace'
StandardLib.All                = require './all'
StandardLib.Promise            = require './promise'
StandardLib.PromisedFileReader = require './promised_file_reader'
StandardLib.finishLoad(
  ["All","Promise","PromisedFileReader"]
)