# generated by Neptune Namespaces
# file: art/foundation/standard_lib/index.coffee

module.exports =
StandardLib                     = require './namespace'
StandardLib.All                 = require './all'
StandardLib.ArrayCompactFlatten = require './array_compact_flatten'
StandardLib.ArrayExtensions     = require './array_extensions'
StandardLib.Eq                  = require './eq'
StandardLib.Function            = require './function'
StandardLib.Hash                = require './hash'
StandardLib.Math                = require './math'
StandardLib.Promise             = require './promise'
StandardLib.PromisedFileReader  = require './promised_file_reader'
StandardLib.Regexp              = require './regexp'
StandardLib.Ruby                = require './ruby'
StandardLib.ShallowClone        = require './shallow_clone'
StandardLib.String              = require './string'
StandardLib.StringCase          = require './string_case'
StandardLib.Time                = require './time'
StandardLib.Types               = require './types'
StandardLib.Unique              = require './unique'
StandardLib.finishLoad(
  ["All","ArrayCompactFlatten","ArrayExtensions","Eq","Function","Hash","Math","Promise","PromisedFileReader","Regexp","Ruby","ShallowClone","String","StringCase","Time","Types","Unique"]
)