# generated by Neptune Namespaces
# file: art/foundation/standard_lib/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.StandardLib ||
class Foundation.StandardLib extends Neptune.Base
  @namespace: Foundation
  @namespacePath: "Neptune.Art.Foundation.StandardLib"

Foundation.addNamespace Foundation.StandardLib