# generated by Neptune Namespaces v0.1.0
# file: art/foundation/standard_lib/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.StandardLib ||
Foundation.addNamespace 'StandardLib', class StandardLib extends Neptune.Base
  ;