# generated by Neptune Namespaces v2.x.x
# file: Art/Foundation/Tools/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Tools ||
Foundation.addNamespace 'Tools', class Tools extends Neptune.Base
  ;
