# generated by Neptune Namespaces
# file: art/foundation/index.coffee

(module.exports = require './namespace')
.addModules
  _All:                    require './_all'
  Analytics:               require './analytics'
  BatchLoader:             require './batch_loader'
  CallStack:               require './call_stack'
  Epoch:                   require './epoch'
  GlobalCounts:            require './global_counts'
  JsonStore:               require './json_store'
  RestClient:              require './rest_client'
  SingleObjectTransaction: require './single_object_transaction'
  Stat:                    require './stat'
  Transaction:             require './transaction'
  WebWorker:               require './web_worker'
  WorkerRpc:               require './worker_rpc'
require './async'
require './binary'
require './browser'
require './class_system'
require './standard_lib'