# generated by Neptune Namespaces v0.5
# file: art/foundation/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_foundation'
require './binary'
require './browser'
require './class_system'
require './standard_lib'
require './tools'