# generated by Neptune Namespaces v0.1.0
# file: art/foundation/namespace.coffee

Art = require '../namespace'
module.exports = Art.Foundation ||
Art.addNamespace 'Foundation', class Foundation extends Neptune.Base
  ;