# generated by Neptune Namespaces
# file: art/foundation/namespace.coffee

Art = require '../namespace'
module.exports = Art.Foundation ||
class Art.Foundation extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.Foundation"

Art.addNamespace Art.Foundation