# generated by Neptune Namespaces
# file: art/dev_tools/webpack/index.coffee

module.exports =
Webpack           = require './namespace'
Webpack.HotLoader = require './hot_loader'
Webpack.finishLoad(
  ["HotLoader"]
)