# generated by Neptune Namespaces v0.3.0
# file: art/dev_tools/webpack/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.Webpack ||
DevTools.addNamespace 'Webpack', class Webpack extends Neptune.Base
  ;