# generated by Neptune Namespaces
# file: src/art/dev_tools/webpack/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.Webpack ||
class DevTools.Webpack extends Neptune.Base
  @namespace: DevTools
  @namespacePath: "Neptune.Art.DevTools.Webpack"

DevTools.addNamespace DevTools.Webpack