# generated by Neptune Namespaces v0.4.1
# file: art/foundation/browser/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './_browser')
.addModules
  Cookie:              require './cookie'
  Dom:                 require './dom'
  DomElementFactories: require './dom_element_factories'
  File:                require './file'