# generated by Neptune Namespaces
# file: art/foundation/browser/index.coffee

(module.exports = require './namespace')
.addModules
  Cookie:              require './cookie'
  Dom:                 require './dom'
  DomElementFactories: require './dom_element_factories'
  File:                require './file'
  Parse:               require './parse'
