# generated by Neptune Namespaces v0.1.0
# file: art/foundation/browser/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Browser ||
Foundation.addNamespace class Browser extends Neptune.Base
  ;