# generated by Neptune Namespaces v2.x.x
# file: tests/art/foundation/browser/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DomElementFactories: require './dom_element_factories'
  Uri:                 require './Uri'                  