# generated by Neptune Namespaces v0.4.1
# file: tests/art/foundation/browser/index.coffee

(module.exports = require './namespace')
.addModules
  DomElementFactories: require './dom_element_factories'