# generated by Neptune Namespaces v2.x.x
# file: tests/art/foundation/browser/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Browser ||
Foundation.addNamespace 'Browser', class Browser extends Neptune.Base
  ;
