# generated by Neptune Namespaces v2.x.x
# file: Art/Foundation/Binary/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Binary ||
Foundation.addNamespace 'Binary', class Binary extends Neptune.Base
  ;
