# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/Browser/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Browser'
.addModules
  Cookie:              require './Cookie'             
  Dom:                 require './Dom'                
  DomElementFactories: require './DomElementFactories'
  File:                require './File'               