# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/Browser/namespace.coffee

module.exports = (require '../namespace').addNamespace('Browser', class Browser extends Neptune.PackageNamespace)
