# generated by Neptune Namespaces
# this file: test/art/index.coffee

module.exports =
Art            = require './namespace'
Art.Foundation = require './foundation'
Art.finishLoad(
  []
  ["Foundation"]
)