# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/.DevTools/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Test: require './Test'
require './DomConsole'
require './Webpack'