# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/.DevTools/namespace.coffee

module.exports = (require '../namespace').addNamespace('DevTools', class DevTools extends Neptune.PackageNamespace)
require './DomConsole/namespace';
require './Webpack/namespace'