# generated by Neptune Namespaces
# this file: src/art/dev_tools/test/index.coffee

module.exports =
Test                      = require './namespace'
Test.ArtChai              = require './art_chai'
Test.Mocha                = require './mocha'
Test.MochaBrowserReporter = require './mocha_browser_reporter'
Test.finishLoad(
  ["ArtChai","Mocha","MochaBrowserReporter"]
)