# generated by Neptune Namespaces v0.4.1
# file: art/dev_tools/test/index.coffee

(module.exports = require './namespace')
.addModules
  ArtChai:              require './art_chai'
  Mocha:                require './mocha'
  MochaBrowserReporter: require './mocha_browser_reporter'
  Perf:                 require './perf'