# generated by Neptune Namespaces
# file: src/art/dev_tools/test/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.Test ||
class DevTools.Test extends Neptune.Base
  @namespace: DevTools
  @namespacePath: "Neptune.Art.DevTools.Test"