# generated by Neptune Namespaces v0.3.0
# file: art/dev_tools/test/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.Test ||
DevTools.addNamespace 'Test', class Test extends Neptune.Base
  ;