# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/.DevTools/DomConsole/PseudoReact/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Component: require './Component'