# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/.DevTools/DomConsole/PseudoReact/namespace.coffee

module.exports = (require '../namespace').addNamespace('PseudoReact', class PseudoReact extends Neptune.PackageNamespace)
