# generated by Neptune Namespaces v0.5
# file: tests/art/foundation/async/index.coffee

module.exports = require './namespace'
.addModules
  Basic:           require './basic'           
  ProgressAdapter: require './progress_adapter'