# generated by Neptune Namespaces
# file: tests/art/foundation/async/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Async ||
Foundation.addNamespace class Async extends Neptune.Base
  ;