# generated by Neptune Namespaces v0.4.1
# file: tests/art/foundation/async/namespace.coffee

Foundation = require '../namespace'
module.exports = Foundation.Async ||
Foundation.addNamespace 'Async', class Async extends Neptune.Base
  ;