# generated by Neptune Namespaces
# this file: src/art/dev_tools/profiler/index.coffee

module.exports =
Profiler      = require './namespace'
Profiler.Main = require './main'
Profiler.finishLoad(
  ["Main"]
)