# generated by Neptune Namespaces
# file: src/art/dev_tools/profiler/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.Profiler ||
class DevTools.Profiler extends Neptune.Base
  @namespace: DevTools
  @namespacePath: "Neptune.Art.DevTools.Profiler"