# generated by Neptune Namespaces v1.x.x
# file: Art/Foundation/Tools/ArtConfig/namespace.coffee

Tools = require '../namespace'
module.exports = Tools.ArtConfig ||
Tools.addNamespace 'ArtConfig', class ArtConfig extends Neptune.Base
  ;