# generated by Neptune Namespaces v1.x.x
# file: art/dev_tools/namespace.coffee

Art = require '../namespace'
module.exports = Art.DevTools ||
Art.addNamespace 'DevTools', class DevTools extends Neptune.Base
  ;