# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/.DevTools/DomConsole/namespace.coffee

module.exports = (require '../namespace').addNamespace('DomConsole', class DomConsole extends Neptune.PackageNamespace)
require './PseudoReact/namespace'