# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Foundation'
.addModules
  ArtFoundationConfig: require './ArtFoundationConfig'
  Binary:              require './Binary'             
require './Browser'
require './Tools'