# generated by Neptune Namespaces
# file: art/foundation/class_system/inspect/index.coffee

(module.exports = require './namespace')
.addModules
  Inspector:  require './inspector'
  Inspector2: require './inspector2'
  Main:       require './main'
require './inspected'