# generated by Neptune Namespaces
# file: art/foundation/class_system/inspect/namespace.coffee

ClassSystem = require '../namespace'
module.exports = ClassSystem.Inspect ||
ClassSystem.addNamespace class Inspect extends Neptune.Base
  ;