# generated by Neptune Namespaces v0.1.0
# file: art/foundation/class_system/inspect/namespace.coffee

ClassSystem = require '../namespace'
module.exports = ClassSystem.Inspect ||
ClassSystem.addNamespace 'Inspect', class Inspect extends Neptune.Base
  ;