# generated by Neptune Namespaces v1.x.x
# file: Art/DevTools/DomConsole/PseudoReact/namespace.coffee

DomConsole = require '../namespace'
module.exports = DomConsole.PseudoReact ||
DomConsole.addNamespace 'PseudoReact', class PseudoReact extends Neptune.Base
  ;