# generated by Neptune Namespaces v3.x.x
# file: Art.Foundation/.DevTools/Webpack/namespace.coffee

module.exports = (require '../namespace').addNamespace('Webpack', class Webpack extends Neptune.PackageNamespace)
