# generated by Neptune Namespaces
# file: art/dev_tools/dom_console/index.coffee

module.exports =
DomConsole       = require './namespace'
DomConsole.Chart = require './chart'
DomConsole.Main  = require './main'
DomConsole.finishLoad(
  ["Chart","Main"]
)