# generated by Neptune Namespaces v0.4.1
# file: art/dev_tools/dom_console/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.DomConsole ||
DevTools.addNamespace 'DomConsole', class DomConsole extends Neptune.Base
  ;