# generated by Neptune Namespaces
# file: art/dev_tools/dom_console/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.DomConsole ||
DevTools.addNamespace class DomConsole extends Neptune.Base
  ;