# generated by Neptune Namespaces
# file: src/art/dev_tools/dom_console/namespace.coffee

DevTools = require '../namespace'
module.exports = DevTools.DomConsole ||
class DevTools.DomConsole extends Neptune.Base
  @namespace: DevTools
  @namespacePath: "Neptune.Art.DevTools.DomConsole"